### ISSUE TITLE
Request to create a new web-demos branch.

### ISSUE THREAD

**Issue by ilopX** [RefactoringGuru/design-patterns-dart#23]
Hi @neochief 
Please create new branch "**web-demos**" for Flutter online examples. 
Activate it as GitHub Pages.
Then, I can send you a pull request.

This needs to run Flutter web from your host.
Now it only works with my https://ilopx.github.io/design-patterns-dart/#/observer/subscriber_flutter_widget

**Comment by neochief** [comment]
All right, the branch has been created and set up (the URL is going to be https://refactoringguru.github.io/design-patterns-dart/). Can you check and let me know if you need anything else?

**Comment by neochief** [comment]
And BTW, thanks a lot for all of your contributions.

**Comment by ilopX** [comment]
**Checklist to close this issue:**
- [x] Wait for the approval of the pull request https://github.com/RefactoringGuru/design-patterns-dart/pull/24
- [x] Test https://refactoringguru.github.io/design-patterns-dart/#/adapter/flutter_adapter
- [x] Test https://refactoringguru.github.io/design-patterns-dart/#/observer/subscriber_flutter_widget
